In [ ]:
# pip install pyreadstat
# pip install savReaderWriter

In [1]:
import os
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request
import pyreadstat
import savReaderWriter as sav

In [2]:
#Base REC0111
rec_1 = pd.read_spss ( r"..\..\_data\endes\2019\REC0111.sav", usecols=None, convert_categoricals=True )
rec_1

with sav.SavHeaderReader( r"..\..\_data\endes\2019\REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()
    value_labels1 = metadata.valueLabels
    var_labels1 = metadata.varLabels

In [3]:
#Base REC0111 - Adding values an var lables
rec_1.attrs[ 'value_labels1' ] = metadata.valueLabels
rec_1.attrs[ 'var_labels1' ] = metadata.varLabels

In [4]:
#Base RE223132
rec_2 = pd.read_spss ( r"..\..\_data\endes\2019\RE223132.sav", usecols=None, convert_categoricals=True )
rec_2

with sav.SavHeaderReader( r"..\..\_data\endes\2019\RE223132.sav", ioUtf8=True) as header:
    metadata = header.all()
    value_labels2 = metadata.valueLabels
    var_labels2 = metadata.varLabels

In [5]:
#Base RE223132- Adding values an var lables
rec_2.attrs[ 'value_labels2' ] = metadata.valueLabels
rec_2.attrs[ 'var_labels2' ] = metadata.varLabels

In [6]:
#Base RE516171
rec_3 = pd.read_spss ( r"..\..\_data\endes\2019\RE516171.sav", usecols=None, convert_categoricals=True )
rec_3

with sav.SavHeaderReader( r"..\..\_data\endes\2019\RE516171.sav", ioUtf8=True) as header:
    metadata = header.all()
    value_labels3 = metadata.valueLabels
    var_labels3 = metadata.varLabels

In [7]:
#Base RE516171 - Adding values an var lables
rec_3.attrs[ 'value_labels3' ] = metadata.valueLabels
rec_3.attrs[ 'var_labels3' ] = metadata.varLabels

In [8]:
#Select columns and update values: rec1_1
b1 = ('CASEID', 'V000', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008', 'V009', 'V010', 'V011', 'V012', 
      'V024','V102', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V127', 'V133')
rec1_1 = rec_1.loc [ :, b1 ]
rec1_1

new_value_labels1 = { key: value_labels1 [ key ] for key in b1 if key in value_labels1.keys() }
new_var_labels1 = { key: var_labels1 [ key ] for key in b1 }

In [9]:
#Select columns and update values: rec2_1
b2 = ('CASEID', 'V201', 'V218', 'V301', 'V302', 'V323', 'V323A', 'V325A', 'V326', 'V327', 'V337', 'V359', 'V360', 
                 'V361', 'V362', 'V363', 'V364', 'V367', 'V372', 'V372A', 'V375A', 'V376', 'V376A', 'V379', 'V380')
rec2_1 = rec_2.loc [ :, b2 ]
rec2_1

new_value_labels2 = { key: value_labels2 [ key ] for key in b2 if key in value_labels2.keys() }
new_var_labels2 = { key: var_labels2 [ key ] for key in b2 }

In [10]:
#Select columns and update values: rec3_1
b3= ('CASEID', 'V501', 'V502', 'V503', 'V504', 'V505', 'V506', 'V507', 'V508', 'V509', 'V510', 
                 'V511', 'V512', 'V513', 'V525', 'V613', 'V714', 'V715')
rec3_1 = rec_3.loc [ :, b3 ]
rec3_1

new_value_labels3 = { key: value_labels3 [ key ] for key in b3 if key in value_labels3.keys() }
new_var_labels3 = { key: var_labels3 [ key ] for key in b3 }

In [12]:
#Generate new variable and updte dictionary
rec1_1["year"] = 2019
new_key = {'Year': 'Year of the survey'}
new_var_labels1.update(new_key)
new_var_labels1

{'CASEID': 'Identificación Cuestionario Individual',
 'V000': 'Código y fase del país',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V024': 'Región',
 'V102': 'Tipo de lugar de residencia',
 'V120': 'En su hogar tiene: radio',
 'V121': 'En su hogar tiene: televisión',
 'V122': 'En su hogar tiene: refrigerador',
 'V123': 'En su hogar tiene: bicicleta',
 'V124': 'En su hogar tiene: motocicleta/motocar',
 'V125': 'En su hogar tiene: coche/camión',
 'V127': 'Material predominante del piso de la vivienda',
 'V133': 'Educación en años simples',
 'Year': 'Year of the survey'}

In [13]:
#Merge rec1_1, rec2_1, and rec3_1 using CASEID. Name this new object as endes_2019
endes_2019 = rec1_1.merge(rec2_1, on='CASEID', how='inner')
endes_2019 = endes_2019.merge(rec3_1, on='CASEID', how='inner')
endes_2019

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V508,V509,V510,V511,V512,V513,V525,V613,V714,V715
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,2008.0,1297.0,Tiene mes y año,21.0,11.0,De 10 a 14 años,17.0,2.0,Sí,11.0
1,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,2011.0,1344.0,Tiene mes y año,28.0,7.0,De 5 a 9 años,18.0,3.0,Sí,14.0
2,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1984.0,1016.0,Tiene año - imputa mes,14.0,34.0,De 30 a más años,14.0,0.0,No,6.0
3,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,2009.0,1320.0,Tiene mes y año,18.0,9.0,De 5 a 9 años,15.0,2.0,No,6.0
4,000113601 2,PE6,1.0,136.0,2.0,1.0,2019.0,1434.0,11.0,1988.0,...,2005.0,1272.0,Tiene mes y año,17.0,13.0,De 10 a 14 años,15.0,2.0,Sí,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33306,325406201 2,PE6,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,1985.0,1032.0,Tiene mes y año,14.0,34.0,De 30 a más años,12.0,3.0,No,5.0
33307,325406301 2,PE6,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,2002.0,1236.0,Tiene mes y año,14.0,17.0,De 15 a 19 años,12.0,3.0,No,7.0
33308,325407001 2,PE6,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,1986.0,1043.0,Tiene mes y año,13.0,33.0,De 30 a más años,12.0,4.0,No,5.0
33309,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,2008.0,1301.0,Tiene mes y año,13.0,11.0,De 10 a 14 años,13.0,2.0,No,11.0
33310,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,2013.0,1362.0,Tiene mes y año,16.0,6.0,De 5 a 9 años,15.0,2.0,No,11.0