In [1]:
import pandas as pd
import numpy as np
import os
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
import unidecode
import json
from tqdm import tqdm_notebook as tqdm
import googlemaps

In [3]:
driver = webdriver.Chrome( ChromeDriverManager().install() )
URL = 'https://www.sunedu.gob.pe/lista-universidades/'
driver.get( URL )
driver.maximize_window()

pubtab_path = driver.find_element_by_xpath( '/html/body/div[1]/div[3]/div/div/div[1]/div/div/div/div[1]/div/div[1]/div' )
pubtab_html = pubtab_path.get_attribute( 'innerHTML' )
pub = pd.read_html( pubtab_html )[ 0 ].iloc[ :, 1:4 ]

driver.find_element_by_xpath( "/html/body/div[1]/div[3]/div/div/div[1]/div/div/div/div[1]/ul/li[2]/a" ).click()

prvtab_path = driver.find_element_by_xpath( '/html/body/div[1]/div[3]/div/div/div[1]/div/div/div/div[1]/div/div[2]/div' )
prvtab_html = prvtab_path.get_attribute( 'innerHTML' )
prv = pd.read_html( prvtab_html )[ 0 ].iloc[ :, 1:4 ]

driver.close()

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST chromedriver version for 97.0.4692 google-chrome
Driver [C:\Users\Work\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache
C:\Users\Work\AppData\Local\Temp/ipykernel_3124/588543466.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome( ChromeDriverManager().install() )
C:\Users\Work\AppData\Local\Temp/ipykernel_3124/588543466.py:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  pubtab_path = driver.find_element_by_xpath( '/html/body/div[1]/div[3]/div/div/div[1]/div/div/div/div[1]/div/div[1]/div' )
C:\Users\Work\AppData\Local\Temp/ipykernel_3124/588543466.py:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath( "/html/body/div[1]/div[3]/div/div/div[1]/div/div/div/div[1]/ul/li[2]/a" ).click()
C:\Users\Work\AppData\Local\Temp/ipykernel_3124/588543466.py:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  prvtab_path = driver.find_element_by_xpath( '/html/body/div[1]/div[3]/div/div/div[1]/div/div/div/div[1]/div/div[2]/div' )

In [5]:
pub

,UNIVERSIDAD,DEPARTAMENTO,PROVINCIA
0,Universidad Nacional Mayor de San Marcos,Lima,Lima
1,Universidad Nacional de San Cristóbal de Huamanga,Ayacucho,Huamanga
2,Universidad Nacional de San Antonio Abad del C...,Cusco,Cusco
3,Universidad Nacional de Trujillo,La Libertad,Trujillo
4,Universidad Nacional de San Agustín de Arequipa,Arequipa,Arequipa
5,Universidad Nacional de Ingeniería,Lima,Lima
6,Universidad Nacional Agraria La Molina,Lima,Lima
7,Universidad Nacional San Luis Gonzaga,Ica,Ica
8,Universidad Nacional del Centro del Perú,Junín,Huancayo
9,Universidad Nacional de la Amazonía Peruana,Loreto,Maynas
10,Universidad Nacional del Altiplano,Puno,Puno
11,Universidad Nacional de Piura,Piura,Piura
12,Universidad Nacional de Cajamarca,Cajamarca,Cajamarca
13,Universidad Nacional Federico Villarreal,Lima,Lima
14,Universidad Nacional Agraria de la Selva,Huánuco,Leoncio Prado
15,Universidad Nacional Hermilio Valdizán de Huánuco,Huánuco,Huánuco
16,Universidad Nacional de Educación Enrique Guzm...,Lima,Lima
17,Universidad Nacional Daniel Alcides Carrión,Pasco,Pasco
18,Universidad Nacional del Callao,Callao,Callao
19,Universidad Nacional José Faustino Sánchez Car...,Lima,Huaura
20,Universidad Nacional Pedro Ruiz Gallo,Lambayeque,Lambayeque
21,Universidad Nacional Jorge Basadre Grohmann,Tacna,Tacna
22,Universidad Nacional Santiago Antúnez de Mayolo,Ancash,Huaraz
23,Universidad Nacional de San Martín,San Martín,San Martín
24,Universidad Nacional de Ucayali,Ucayali,Coronel Portillo
25,Universidad Nacional de Tumbes,Tumbes,Tumbes
26,Universidad Nacional del Santa,Ancash,Santa
27,Universidad Nacional de Huancavelica,Huancavelica,Huancavelica
28,Universidad Nacional Amazónica de Madre de Dios,Madre De Dios,Tambopata
29,Universidad Nacional Toribio Rodríguez de Mend...,Amazonas,Chachapoyas
30,Universidad Nacional Micaela Bastidas de Apurímac,Apurímac,Abancay
31,Universidad Nacional Intercultural de la Amazonía,Ucayali,Coronel Portillo
32,Universidad Nacional Tecnológica de Lima Sur (*1),Lima,Lima
33,Universidad Nacional José María Arguedas,Apurímac,Andahuaylas
34,Universidad Nacional de Moquegua,Moquegua,Mariscal Nieto
35,Universidad Nacional de Juliaca,Puno,San Román
36,Universidad Nacional de Jaén,Cajamarca,Jaén
37,Universidad Nacional de Frontera,Piura,Sullana
38,Universidad Nacional Autónoma de Chota,Cajamarca,Chota
39,Universidad Nacional de Barranca,Lima,Barranca
40,Universidad Nacional de Cañete,Lima,Cañete
41,Universidad Nacional Intercultural Fabiola Sal...,Amazonas,Bagua
42,Universidad Nacional Intercultural de la Selva...,Junín,Chanchamayo
43,Universidad Nacional Intercultural de Quillabamba,Cusco,La Convención
44,Universidad Nacional Autónoma de Alto Amazonas,Loreto,Alto Amazonas
45,Universidad Nacional Autónoma Altoandina de Tarma,Junín,Tarma
46,Universidad Nacional Autónoma de Huanta,Ayacucho,Huanta
47,Universidad Nacional Tecnológica de San Juan d...,Lima,Lima
48,Universidad Autónoma Municipal de Los Olivos,Lima,Lima
49,Universidad Nacional Autónoma de Tayacaja Dani...,Huancavelica,Tayacaja
50,Universidad Nacional Ciro Alegría,La Libertad,Sanchez Carrión

In [6]:
prv

                                          UNIVERSIDAD DEPARTAMENTO PROVINCIA
0            Pontificia Universidad Católica del Perú         Lima      Lima
1                Universidad Peruana Cayetano Heredia         Lima      Lima
2                 Universidad Católica de Santa María     Arequipa  Arequipa
3                            Universidad del Pacífico         Lima      Lima
4                                 Universidad de Lima         Lima      Lima
..                                                ...          ...       ...
87  Universidad Santo Tomás de Aquino de Ciencia e...        Junín  Huancayo
88                           Universidad Privada SISE         Lima      Lima
89     Universidad Seminario Evangélico de Lima (*12)         Lima      Lima
90         Universidad Seminario Bíblico Andino (*12)         Lima      Lima
91                      Universidad Católica San José         Lima      Lima

[92 rows x 3 columns]

In [17]:
univs = pub.append( prv ).reset_index( drop = True )

In [18]:
univs

                                           UNIVERSIDAD DEPARTAMENTO PROVINCIA
0             Universidad Nacional Mayor de San Marcos         Lima      Lima
1    Universidad Nacional de San Cristóbal de Huamanga     Ayacucho  Huamanga
2    Universidad Nacional de San Antonio Abad del C...        Cusco     Cusco
3                     Universidad Nacional de Trujillo  La Libertad  Trujillo
4      Universidad Nacional de San Agustín de Arequipa     Arequipa  Arequipa
..                                                 ...          ...       ...
138  Universidad Santo Tomás de Aquino de Ciencia e...        Junín  Huancayo
139                           Universidad Privada SISE         Lima      Lima
140     Universidad Seminario Evangélico de Lima (*12)         Lima      Lima
141         Universidad Seminario Bíblico Andino (*12)         Lima      Lima
142                      Universidad Católica San José         Lima      Lima

[143 rows x 3 columns]

In [37]:
key = 'AIzaSyCDr79v4CHSAmF-drAZQqtR_Bh2gIFr1wo'

In [52]:
def uni_geo( row ):
    
    query = f"{ row[ 'UNIVERSIDAD' ] }, { row[ 'DEPARTAMENTO' ] }, { row[ 'PROVINCIA' ] }"
    
    gmaps = googlemaps.Client( key = key )
    result_api = gmaps.geocode( query , region = 'PE' )
    
    try:
        lat = result_api[0]['geometry']['location']['lat']
        lon = result_api[0]['geometry']['location']['lng']   
    except:
        lat = np.nan
        lon = np.nan
    
    return  ( lat, lon )

In [53]:
uni_geo( univs.iloc[ -2, : ] )

(-12.0696208, -77.0533978)

In [54]:
univs[ 'COORDS' ] = univs.apply( lambda row: uni_geo( row ), axis = 1 )

ValueError: too many values to unpack (expected 2)

In [68]:
univs[ 'Latitude_univ' ] = univs[ 'COORDS' ].apply( lambda x: [ y for y in x ][ 0 ] )
univs[ 'Longitude_univ' ] = univs[ 'COORDS' ].apply( lambda x: [ y for y in x ][ 1 ] )

In [72]:
univs = univs.drop( ['COORDS' ], axis = 1 )

In [101]:
univs[ 'DEPARTAMENTO' ] = univs[ 'DEPARTAMENTO' ].apply( lambda x: unidecode.unidecode( x.upper() ) )

In [102]:
univs.to_csv( r'_data/univs.csv', index = False, encoding = 'UTF-8-SIG' )

In [103]:
centroids = pd.read_excel( r'../../_data/peru_departments_centroids.xlsx' )

In [104]:
centroids

,CCDD,NOMBDEP,CAPITAL,Dpt_Centroid_Latitude,Dpt_Centroid_Longitude
0,1,AMAZONAS,CHACHAPOYAS,-5.069369,-78.055235
1,2,ANCASH,HUARAZ,-9.406368,-77.670229
2,3,APURIMAC,ABANCAY,-14.028147,-72.974732
3,4,AREQUIPA,AREQUIPA,-15.844475,-72.472918
4,5,AYACUCHO,AYACUCHO,-14.086284,-74.083968
5,6,CAJAMARCA,CAJAMARCA,-6.432297,-78.745878
6,7,CALLAO,CALLAO,-11.940800,-77.126022
7,8,CUSCO,CUSCO,-13.189060,-72.170789
8,9,HUANCAVELICA,HUANCAVELICA,-13.023206,-75.002090
9,10,HUANUCO,HUANUCO,-9.416089,-76.024205
10,11,ICA,ICA,-14.233761,-75.574814
11,12,JUNIN,HUANCAYO,-11.538922,-74.876839
12,13,LA LIBERTAD,TRUJILLO,-7.921689,-78.368017
13,14,LAMBAYEQUE,CHICLAYO,-6.340478,-79.826995
14,15,LIMA,LIMA,-11.785115,-76.628934
15,16,LORETO,IQUITOS,-4.114622,-74.412649
16,17,MADRE DE DIOS,PUERTO MALDONADO,-11.982106,-70.530759
17,18,MOQUEGUA,MOQUEGUA,-16.858546,-70.837182
18,19,PASCO,CERRO DE PASCO,-10.398817,-75.297587
19,20,PIURA,PIURA,-5.127846,-80.336263
20,21,PUNO,PUNO,-14.923763,-69.950299
21,22,SAN MARTIN,MOYOBAMBA,-7.033278,-76.714790
22,23,TACNA,TACNA,-17.644209,-70.276149
23,24,TUMBES,TUMBES,-3.856391,-80.544689
24,25,UCAYALI,PUCALLPA,-9.623529,-73.430992

In [105]:
data = univs.merge( centroids, left_on = 'DEPARTAMENTO', right_on = 'NOMBDEP', validate = 'm:1')

In [106]:
data

,UNIVERSIDAD,DEPARTAMENTO,PROVINCIA,Latitude_univ,Longitude_univ,CCDD,NOMBDEP,CAPITAL,Dpt_Centroid_Latitude,Dpt_Centroid_Longitude
0,Universidad Nacional Mayor de San Marcos,LIMA,Lima,-12.056158,-77.084520,15,LIMA,LIMA,-11.785115,-76.628934
1,Universidad Nacional de Ingeniería,LIMA,Lima,-12.023179,-77.047630,15,LIMA,LIMA,-11.785115,-76.628934
2,Universidad Nacional Agraria La Molina,LIMA,Lima,-12.081749,-76.943190,15,LIMA,LIMA,-11.785115,-76.628934
3,Universidad Nacional Federico Villarreal,LIMA,Lima,-12.047555,-77.040452,15,LIMA,LIMA,-11.785115,-76.628934
4,Universidad Nacional de Educación Enrique Guzm...,LIMA,Lima,-12.066301,-76.953765,15,LIMA,LIMA,-11.785115,-76.628934
...,...,...,...,...,...,...,...,...,...,...
138,Universidad Nacional Micaela Bastidas de Apurímac,APURIMAC,Abancay,-13.617553,-72.868163,3,APURIMAC,ABANCAY,-14.028147,-72.974732
139,Universidad Nacional José María Arguedas,APURIMAC,Andahuaylas,-13.657295,-73.387906,3,APURIMAC,ABANCAY,-14.028147,-72.974732
140,Universidad Tecnológica de los Andes,APURIMAC,Abancay,-13.632333,-72.887178,3,APURIMAC,ABANCAY,-14.028147,-72.974732
141,Universidad Nacional de Moquegua,MOQUEGUA,Mariscal Nieto,-17.190051,-70.936586,18,MOQUEGUA,MOQUEGUA,-16.858546,-70.837182
142,Universidad José Carlos Mariátegui (*2),MOQUEGUA,Mariscal Nieto,-17.190029,-70.942387,18,MOQUEGUA,MOQUEGUA,-16.858546,-70.837182

array(['LIMA', 'AYACUCHO', 'CUSCO', 'LA LIBERTAD', 'AREQUIPA', 'ICA',
       'JUNÍN', 'LORETO', 'PUNO', 'PIURA', 'CAJAMARCA', 'HUÁNUCO',
       'PASCO', 'CALLAO', 'LAMBAYEQUE', 'TACNA', 'ANCASH', 'SAN MARTÍN',
       'UCAYALI', 'TUMBES', 'HUANCAVELICA', 'MADRE DE DIOS', 'AMAZONAS',
       'APURÍMAC', 'MOQUEGUA'], dtype=object)