# 1 Assignment 3

1. Generate a function named **beta_OLS**. This function must return the estimated beta using OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The function's output must be a **pd.DataFrame** (`n`, 1) where `n` is the total number of regressors ( it includes the **Intercept** when `intercept` is `True`). The column should be named as **Coef.** and the row index should be named as the original name of the columns in `X` input. Your results should look like `beta_OLS_output`. Apply your function to find $\widehat{\boldsymbol{\beta}}^{(OLS)}$ of the equation below. Use `data`.  **Hint: Use NumPy to generate the OLS beta and check [this link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) to change the index name of a pd.Dataframe, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\beta}}^{(OLS)} = \left( \mathbf{X}^\top \mathbf{X}\right)^{-1} \mathbf{X}^\top \mathbf{Y}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [3]:
import pandas as pd
import numpy as np
import pickle
import scipy.stats as stats

In [4]:
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [5]:
greene

,id,YEAR,COST,Q,PL,SL,PK,SK,PF,SF
0,1,1970,0.2130,8.0,6869.47,0.3291,64.945,0.4197,18.000,0.2512
1,4,1970,3.0427,869.0,8372.96,0.1030,68.227,0.2913,21.067,0.6057
2,5,1970,9.4059,1412.0,7960.90,0.0891,40.692,0.1567,41.530,0.7542
3,14,1970,0.7606,65.0,8971.89,0.2802,41.243,0.1282,28.539,0.5916
4,15,1970,2.2587,295.0,8218.40,0.1772,71.940,0.1623,39.200,0.6606
...,...,...,...,...,...,...,...,...,...,...
153,214,1970,6.8293,946.6,10642.16,0.0883,43.600,0.1914,51.463,0.7203
154,215,1970,3.7605,377.0,7432.24,0.2117,74.120,0.2274,33.436,0.5609
155,216,1970,3.9822,391.0,5826.04,0.1926,78.288,0.0924,44.633,0.7151
156,217,1970,30.1880,5317.0,9586.63,0.0845,78.008,0.2009,41.840,0.7147
157,218,1970,67.8562,15220.0,6986.09,0.1451,74.025,0.2596,25.662,0.5945

In [6]:
file_to_open = open( r'../../_data/data_greene.pkl' , "rb" )
data = pickle.load( file_to_open )

In [7]:
lnct = np.log(ct)
lnq = np.log(q)
lnp1 = np.log(p1)
lnp2 = np.log(p2)
lnp3 = np.log(p3)

In [8]:
lnq2 = np.multiply(lnq,lnq)
lnqlnp1 = np.multiply(lnq,lnp1)
lnqlnp2 = np.multiply(lnq,lnp2)
lnqlnp3 = np.multiply(lnq,lnp3)

In [9]:
lnp1_2 = np.multiply(lnp1,lnp1) 
lnp2_2 = np.multiply(lnp2,lnp2) 
lnp3_2 = np.multiply(lnp3,lnp3)

In [10]:
lnp1lnp2 = np.multiply (lnp1,lnp2)
lnp1lnp3 = np.multiply (lnp1,lnp3)
lnp2lnp3 = np.multiply (lnp2,lnp3)

In [11]:
import statsmodels.formula.api as smf
result = smf.ols( 'lnct ~ lnq + lnq2 + lnqlnp1 + lnqlnp2 + lnqlnp3 + lnp1 + lnp2 + lnp3 + lnp1_2 + lnp2_2 + lnp3_2 + lnp1lnp2 + lnp1lnp3 + lnp2lnp3',
                  data = greene)

In [12]:
X_test = pd.DataFrame(result.exog, columns = result.exog_names).iloc[ : , 1: ]

In [13]:
y_test = pd.Series(result.endog , name = result.endog_names )

In [14]:
intercept_test = True

In [15]:
beta_OLS_output_test = result.fit().summary2().tables[1].iloc[ :, [0]]

In [16]:
file_to_open = open( r'../../_data/beta_OLS_output.pkl' , "rb" )
beta_OLS_output = pickle.load( file_to_open )
beta_OLS_output

                  Coef.
Intercept    -76.259259
lnq           -1.080425
(lnq)^2        0.026489
(lnq)(lnp1)    0.131041
(lnq)(lnp2)    0.058652
(lnq)(lnp3)    0.040144
lnp1          14.718292
lnp2          -0.894733
lnp3           6.380797
(lnp1)^2      -1.538527
(lnp2)^2      -0.073506
(lnp3)^2      -0.327414
(lnp1)(lnp2)   0.324566
(lnp1)(lnp3)  -1.144101
(lnp2)(lnp3)  -0.048049

In [17]:
beta_OLS_output_test

               Coef.
Intercept -76.259261
lnq        -1.080425
lnq2        0.026489
lnqlnp1     0.131041
lnqlnp2     0.058652
lnqlnp3     0.040144
lnp1       14.718293
lnp2       -0.894733
lnp3        6.380797
lnp1_2     -0.769264
lnp2_2     -0.036753
lnp3_2     -0.163707
lnp1lnp2    0.162283
lnp1lnp3   -0.572050
lnp2lnp3   -0.024025

In [18]:
X_input = pd.DataFrame()
y_input = pd.DataFrame()

In [19]:
y_input['lnct'] = lnct
X_input['lnq'] = lnq
X_input['lnq2'] = lnq2
X_input['lnqlnp1'] = lnqlnp1
X_input['lnqlnp2'] = lnqlnp2
X_input['lnqlnp3'] = lnqlnp3
X_input['lnp1'] = lnp1
X_input['lnp2'] = lnp2
X_input['lnp3'] = lnp3
X_input['lnp1_2'] = lnp1_2
X_input['lnp2_2'] = lnp2_2
X_input['lnp3_2'] = lnp3_2
X_input['lnp1lnp2'] = lnp1lnp2
X_input['lnp1lnp3'] = lnp1lnp3
X_input['lnp2lnp3'] = lnp2lnp3

In [20]:
def B_OLS(X:pd.DataFrame, y:pd.Series, intercept:bool=True) -> pd.DataFrame:
    
    if not isinstance(X, pd.DataFrame):
        raise TypeError('X is not DF')
        
    if not isinstance(y, pd.DataFrame):
        raise TypeError('y is not a pd S')
        
    if not isinstance(intercept, bool):
        raise TypeError('intercept is not B')
    
    if intercept:
        X_ = X.copy()
        X_.insert(0, 'Intercept', 1)
        betas = np.linalg.inv(X_.T @ X_) @ X_.T @ y
        betas['Params'] = X_.columns.tolist()
        betas.set_index('Params', inplace=True)
        betas.rename(columns={'lnct':'Coefs'}, inplace=True)
        return betas
    else:
        betas = np.linalg.inv(X.T @ X) @ X.T @ y
        betas['Params'] = X.columns.tolist()
        betas.set_index('Params', inplace=True)
        betas.rename(columns={'lnct':'Coefs'}, inplace=True)
        return betas

In [21]:
coef=B_OLS (X_input,y_input )
coef

               Coefs
Params
Intercept -76.259258
lnq        -1.080425
lnq2        0.026489
lnqlnp1     0.131041
lnqlnp2     0.058652
lnqlnp3     0.040144
lnp1       14.718292
lnp2       -0.894733
lnp3        6.380797
lnp1_2     -0.769264
lnp2_2     -0.036753
lnp3_2     -0.163707
lnp1lnp2    0.162283
lnp1lnp3   -0.572050
lnp2lnp3   -0.024025

2. Generate a new function named **var_OLS**. This function must return the estimated variance for OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated variance does not include **intercept** in the `X` regressor. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The output of the function should look like `var_OLS_output` where the columns and the index use the name of `X` columns.  Apply your function to find $\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)})$ of the equation below. Use greene data.  **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\varepsilon}} = \mathbf{Y} - \mathbf{X} \widehat{\boldsymbol{\beta}}_{OLS}
$$

$$
\widehat{\sigma}^2_{OLS} = \dfrac{\widehat{\boldsymbol{\varepsilon}}^\top \widehat{\boldsymbol{\varepsilon}}}{N - (k+1)}
$$


$$
\begin{aligned}
\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)}) = 
\sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [34]:
file_to_open = open( r'../../_data/var_OLS_output.pkl' , "rb" )
var_OLS_output = pickle.load( file_to_open )

In [26]:
var_OLS_output = result.fit().cov_params()
var_OLS_output

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1465.361176,0.192537,-0.011698,-0.026677,0.015949,0.039538,-262.932577,-8.392679,-128.192050,11.880857,-0.266944,3.540639,0.990253,10.902441,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,0.000161,-0.006089,-0.186223,0.148320,-0.090714,0.015321,0.000381,-0.000898,-0.015046,0.017546,-0.003570
lnq2,-0.011698,0.000308,0.000006,-0.000036,-0.000005,-0.000011,0.001491,0.001052,0.000862,-0.000043,0.000013,-0.000060,-0.000099,-0.000014,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,-0.000168,0.000348,0.021561,-0.015127,0.005430,-0.001961,0.000019,0.000285,0.001850,-0.001141,-0.000085
lnqlnp2,0.015949,0.000161,-0.000005,-0.000168,0.000653,-0.000189,-0.008293,0.003306,0.008035,0.000587,-0.000170,-0.000103,-0.000170,-0.000144,-0.001375
lnqlnp3,0.039538,-0.006089,-0.000011,0.000348,-0.000189,0.000888,-0.000337,-0.008853,0.000268,0.000211,-0.000033,-0.000067,0.000102,-0.001537,0.002212
lnp1,-262.932577,-0.186223,0.001491,0.021561,-0.008293,-0.000337,50.194723,-1.253531,19.099543,-2.388986,0.070493,-0.420154,0.038416,-1.788158,0.132157
lnp2,-8.392679,0.148320,0.001052,-0.015127,0.003306,-0.008853,-1.253531,8.078742,-0.214871,0.161643,-0.058647,-0.033147,-0.685050,0.199482,-0.367388
lnp3,-128.192050,-0.090714,0.000862,0.005430,0.008035,0.000268,19.099543,-0.214871,20.513715,-0.705214,0.023665,-0.763050,0.036229,-1.555553,-0.072591
lnp1_2,11.880857,0.015321,-0.000043,-0.001961,0.000587,0.000211,-2.388986,0.161643,-0.705214,0.119855,-0.003079,0.011353,-0.013413,0.070381,-0.006656
lnp2_2,-0.266944,0.000381,0.000013,0.000019,-0.000170,-0.000033,0.070493,-0.058647,0.023665,-0.003079,0.008285,-0.002049,-0.001552,-0.002485,0.004467
lnp3_2,3.540639,-0.000898,-0.000060,0.000285,-0.000103,-0.000067,-0.420154,-0.033147,-0.763050,0.011353,-0.002049,0.048556,0.008386,0.043314,-0.006653
lnp1lnp2,0.990253,-0.015046,-0.000099,0.001850,-0.000170,0.000102,0.038416,-0.685050,0.036229,-0.013413,-0.001552,0.008386,0.072939,-0.015413,0.009949
lnp1lnp3,10.902441,0.017546,-0.000014,-0.001141,-0.000144,-0.001537,-1.788158,0.199482,-1.555553,0.070381,-0.002485,0.043314,-0.015413,0.138302,-0.010534
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,-0.001375,0.002212,0.132157,-0.367388,-0.072591,-0.006656,0.004467,-0.006653,0.009949,-0.010534,0.060678

In [28]:
def var_OLS( X : pd.DataFrame, y : pd.Series, intercept = True ):
        
    if not isinstance( X, pd.DataFrame ):
        raise TypeError( 'X is not DF' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd S' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not B' )
        
    if len( X ) != len( y ):
        raise ValueError( 'rows in x and y differ' )
    
    X_mat = X.copy()
    y_vec = y.copy()
    
    if intercept == True:
        const = np.ones( len( X_mat ) )
        X_mat.insert(0, "Intercept", const)
    
    var_names = list( X_mat.columns )
    X_mat = X_mat.to_numpy()
    y_vec = y_vec.to_numpy()
    
    xtx_inv = np.linalg.inv( np.dot( np.transpose( X_mat ), X_mat ) )
    coefs = np.dot( xtx_inv, np.dot( np.transpose( X_mat ), y_vec ) )
    
    errores=np.add(y_vec,-np.dot( X_mat , coefs ))
    var_error=np.dot(np.transpose(errores),errores)/(len(errores)-4-1)

    var_coef=var_error*xtx_inv
    
    var_coef = pd.DataFrame( var_coef, index = var_names, columns=var_names)

    
    return var_coef

In [33]:
var_OLS(X_test,y_test ,True)

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1369.585869,0.179953,-0.010933,-0.024934,0.014906,0.036954,-245.747429,-7.844138,-119.813480,11.104330,-0.249497,3.309224,0.925531,10.189862,0.184531
lnq,0.179953,0.131816,0.000288,-0.012580,0.000150,-0.005691,-0.174052,0.138626,-0.084785,0.014319,0.000356,-0.000839,-0.014063,0.016400,-0.003337
lnq2,-0.010933,0.000288,0.000005,-0.000034,-0.000005,-0.000010,0.001394,0.000983,0.000805,-0.000040,0.000012,-0.000056,-0.000092,-0.000013,-0.000045
lnqlnp1,-0.024934,-0.012580,-0.000034,0.001370,-0.000157,0.000325,0.020152,-0.014139,0.005075,-0.001833,0.000018,0.000267,0.001729,-0.001067,-0.000079
lnqlnp2,0.014906,0.000150,-0.000005,-0.000157,0.000610,-0.000177,-0.007751,0.003090,0.007510,0.000549,-0.000159,-0.000096,-0.000159,-0.000135,-0.001285
lnqlnp3,0.036954,-0.005691,-0.000010,0.000325,-0.000177,0.000830,-0.000315,-0.008275,0.000251,0.000197,-0.000031,-0.000063,0.000095,-0.001437,0.002068
lnp1,-245.747429,-0.174052,0.001394,0.020152,-0.007751,-0.000315,46.914020,-1.171601,17.851206,-2.232843,0.065886,-0.392693,0.035905,-1.671285,0.123519
lnp2,-7.844138,0.138626,0.000983,-0.014139,0.003090,-0.008275,-1.171601,7.550720,-0.200827,0.151078,-0.054814,-0.030981,-0.640275,0.186444,-0.343376
lnp3,-119.813480,-0.084785,0.000805,0.005075,0.007510,0.000251,17.851206,-0.200827,19.172949,-0.659121,0.022118,-0.713178,0.033861,-1.453883,-0.067846
lnp1_2,11.104330,0.014319,-0.000040,-0.001833,0.000549,0.000197,-2.232843,0.151078,-0.659121,0.112022,-0.002878,0.010611,-0.012536,0.065781,-0.006221
lnp2_2,-0.249497,0.000356,0.000012,0.000018,-0.000159,-0.000031,0.065886,-0.054814,0.022118,-0.002878,0.007743,-0.001915,-0.001451,-0.002323,0.004175
lnp3_2,3.309224,-0.000839,-0.000056,0.000267,-0.000096,-0.000063,-0.392693,-0.030981,-0.713178,0.010611,-0.001915,0.045382,0.007838,0.040483,-0.006218
lnp1lnp2,0.925531,-0.014063,-0.000092,0.001729,-0.000159,0.000095,0.035905,-0.640275,0.033861,-0.012536,-0.001451,0.007838,0.068172,-0.014406,0.009299
lnp1lnp3,10.189862,0.016400,-0.000013,-0.001067,-0.000135,-0.001437,-1.671285,0.186444,-1.453883,0.065781,-0.002323,0.040483,-0.014406,0.129263,-0.009845
lnp2lnp3,0.184531,-0.003337,-0.000045,-0.000079,-0.001285,0.002068,0.123519,-0.343376,-0.067846,-0.006221,0.004175,-0.006218,0.009299,-0.009845,0.056712

3. Generate a new function named as `reg_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the output does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `reg_OLS_ouput` Apply your function to the equation below. Use greene data.**Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

$$
\widehat{\boldsymbol{\varepsilon}} = \mathbf{Y} - \mathbf{X} \widehat{\boldsymbol{\beta}}_{RLS}
$$

$$
\widehat{\sigma}^2_{RLS} = \dfrac{\widehat{\boldsymbol{\varepsilon}}^\top \widehat{\boldsymbol{\varepsilon}}}{N - (k+1 - M)}
$$

In [18]:
file_to_open = open( r'../../_data/reg_OLS_output.pkl' , "rb" )
reg_OLS_output = pickle.load( file_to_open )
reg_OLS_output

,Coef.,Std.Err.,t,P>|t|,[0.025,0.975]
Intercept,-76.259259,38.280036,-1.992142,4.825953e-02,-151.927107,-0.591411
lnq,-1.080425,0.375545,-2.876952,4.630885e-03,-1.822762,-0.338088
(lnq)^2,0.026489,0.002357,11.240060,2.112040e-21,0.021831,0.031148
(lnq)(lnp1),0.131041,0.038284,3.422854,8.084865e-04,0.055365,0.206716
(lnq)(lnp2),0.058652,0.025549,2.295650,2.315002e-02,0.008149,0.109155
(lnq)(lnp3),0.040144,0.029791,1.347518,1.799447e-01,-0.018744,0.099033
lnp1,14.718292,7.084823,2.077440,3.954949e-02,0.713777,28.722807
lnp2,-0.894733,2.842313,-0.314790,7.533796e-01,-6.513111,4.723645
lnp3,6.380797,4.529207,1.408811,1.610617e-01,-2.572051,15.333645
(lnp1)^2,-1.538527,0.692403,-2.222011,2.785341e-02,-2.907195,-0.169860
(lnp2)^2,-0.073506,0.182039,-0.403791,6.869699e-01,-0.433340,0.286329
(lnp3)^2,-0.327414,0.440709,-0.742927,4.587448e-01,-1.198560,0.543731
(lnp1)(lnp2),0.324566,0.540144,0.600888,5.488659e-01,-0.743132,1.392263
(lnp1)(lnp3),-1.144101,0.743781,-1.538224,1.262037e-01,-2.614326,0.326124
(lnp2)(lnp3),-0.048049,0.492659,-0.097531,9.224414e-01,-1.021884,0.925785

4. Generate a new function named as `restricted_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`,  `L`, `r`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series**,  `L` (coef) must be a **np.array**, `r` must be a **np.array**,  and `intercept` can be `True` or `False`.  When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `restricted_OLS_ouput`. Apply your function to the equation below. Use greene data.
 **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\hat{\boldsymbol{\beta}}^{(RLS)} =\hat{\boldsymbol{\beta}}^{(OLS)} - \left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \left( \boldsymbol{L}\left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \right)^{-1} \left( \boldsymbol{L}\widehat{\boldsymbol{\beta}}^{(OLS)} - \boldsymbol{r} \right)
$$

$$
\begin{aligned}
\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right) 
&= \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1} - \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}  \mathbf{L}^\top \left( \mathbf{L}\left( \mathbf{X}^\top \mathbf{X} \right)^{-1} \mathbf{L}^\top \right)^{-1}  \mathbf{L} \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

In [19]:
L = np.array( ( [ 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0 ], 
              [ 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 
              [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0 ], 
              [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1 ], 
              [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1 ] ) )

r = np.array(  [  1,  0,  0,  0,  0  ]  ).reshape( -1 , 1 )

In [23]:
file_to_open = open( r'../../_data/restricted_OLS_output.pkl' , "rb" )
restricted_OLS_output = pickle.load( file_to_open )
restricted_OLS_output

                 Coef.  Std.Err.          t         P>|t|     [0.025    0.975]
Intercept    -7.111200  2.755866  -2.580387  1.091364e-02 -12.560384 -1.662016
lnq           0.461368  0.119721   3.853679  1.776124e-04   0.224642  0.698094
(lnq)^2       0.029978  0.002121  14.134763  1.312279e-28   0.025784  0.034171
(lnq)(lnp1)  -0.004354  0.022880  -0.190311  8.493452e-01  -0.049596  0.040887
(lnq)(lnp2)   0.036778  0.024201   1.519668  1.308823e-01  -0.011075  0.084631
(lnq)(lnp3)  -0.032424  0.021419  -1.513780  1.323685e-01  -0.074775  0.009928
lnp1          0.215566  1.015206   0.212338  8.321570e-01  -1.791804  2.222936
lnp2          0.402923  0.554162   0.727085  4.684055e-01  -0.692824  1.498670
lnp3          0.381511  0.531316   0.718048  4.739416e-01  -0.669063  1.432084
(lnp1)^2     -0.008712  0.140961  -0.061806  9.508067e-01  -0.287435  0.270011
(lnp2)^2      0.005156  0.160333   0.032156  9.743940e-01  -0.311871  0.322182
(lnp3)^2     -0.015302  0.300316  -0.050952  9.594375e-01  -0.609117  0.578514
(lnp1)(lnp2) -0.005873  0.227732  -0.025787  9.794644e-01  -0.456168  0.444423
(lnp1)(lnp3)  0.014585  0.147324   0.098998  9.212832e-01  -0.276719  0.305888
(lnp2)(lnp3)  0.000717  0.231445   0.003097  9.975331e-01  -0.456920  0.458354

5. Generate a new class named `RegClass`. The initial attributes of your class must be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. Also, you must specify the type of your class' parameters, and output and It must raise an error if the inputs do not meet the requirements.  This class should have two methods: `reg_OLS` and `restricted_OLS` (You can add more if you think it is necessary). These methods should return the same output as the previously defined functions with the same name. The method `reg_OLS` does not need an extra parameter to be executed. After executing the method `reg_OLS`, any user should access the following attributes: `beta_OLS` and `var_OLS`. They should look like `beta_OLS_output` and `var_OLS_output`. The `restricted_OLS` method needs two extra parameters before being executed, `L` and `r`. They refer to the restrictions. After running the method `restricted_OLS`, any user should access the following attributes: `beta_OLS`, `var_OLS`, `rest_beta_OLS`, and `rest_var_OLS`. These attributes refer to the beta and variance estimated using OLS and restricted OLS. They should look like  `beta_OLS_output` and `var_OLS_output`. Fix all the methods and attributes. No user should be able to change them. **Hint: Use [lecture 6](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f362f4c6563747572655f362e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_6%2FLecture_6.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96#6.3.).**