# 1 Assignment 3

1. Generate a function named **beta_OLS**. This function must return the estimated beta using OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The function's output must be a **pd.DataFrame** (`n`, 1) where `n` is the total number of regressors ( it includes the **Intercept** when `intercept` is `True`). The column should be named as **Coef.** and the row index should be named as the original name of the columns in `X` input. Your results should look like `output_example` being `X_input`, `y_input` and `intercept_input` your inputs. Apply your function to find $\widehat{\boldsymbol{\beta}}^{(OLS)}$ of the equation below. Use greene data.  **Hint: Use NumPy to generate the OLS beta and check [this link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) to change the index name of a pd.Dataframe, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\beta}}^{(OLS)} = \left( \mathbf{X}^\top \mathbf{X}\right)^{-1} \mathbf{X}^\top \mathbf{Y}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [3]:
import pandas as pd
import numpy as np
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [4]:
greene

,id,YEAR,COST,Q,PL,SL,PK,SK,PF,SF
0,1,1970,0.2130,8.0,6869.47,0.3291,64.945,0.4197,18.000,0.2512
1,4,1970,3.0427,869.0,8372.96,0.1030,68.227,0.2913,21.067,0.6057
2,5,1970,9.4059,1412.0,7960.90,0.0891,40.692,0.1567,41.530,0.7542
3,14,1970,0.7606,65.0,8971.89,0.2802,41.243,0.1282,28.539,0.5916
4,15,1970,2.2587,295.0,8218.40,0.1772,71.940,0.1623,39.200,0.6606
...,...,...,...,...,...,...,...,...,...,...
153,214,1970,6.8293,946.6,10642.16,0.0883,43.600,0.1914,51.463,0.7203
154,215,1970,3.7605,377.0,7432.24,0.2117,74.120,0.2274,33.436,0.5609
155,216,1970,3.9822,391.0,5826.04,0.1926,78.288,0.0924,44.633,0.7151
156,217,1970,30.1880,5317.0,9586.63,0.0845,78.008,0.2009,41.840,0.7147
157,218,1970,67.8562,15220.0,6986.09,0.1451,74.025,0.2596,25.662,0.5945

In [5]:
import statsmodels.formula.api as smf

In [6]:
results = smf.ols( 'np.log( COST ) ~ np.log( Q ) + np.log(PL)+ np.log(PF) + np.log(PK)', data = greene)

In [16]:
#Definition of variables
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [9]:
X_input = pd.DataFrame(results.exog, columns = results.exog_names).iloc[ : , 1: ]
y_input = pd.Series(results.endog , name = results.endog_names )
intercept_input = True

In [10]:
beta_OLS_output = results.fit().summary2().tables[1].iloc[ :, [0]]

In [11]:
beta_OLS_output

               Coef.
Intercept  -7.472227
np.log(Q)   0.838111
np.log(PL)  0.044258
np.log(PF)  0.713098
np.log(PK)  0.188449

In [12]:
y_input

0     -1.546463
1      1.112745
2      2.241337
3     -0.273648
4      0.814789
         ...
153    1.921222
154    1.324552
155    1.381834
156    3.407444
157    4.217391
Name: np.log(COST), Length: 158, dtype: float64

In [13]:
X_input

     np.log(Q)  np.log(PL)  np.log(PF)  np.log(PK)
0     2.079442    8.834842    2.890372    4.173541
1     6.767343    9.032763    3.047708    4.222840
2     7.252762    8.982297    3.726416    3.706032
3     4.174387    9.101852    3.351272    3.719481
4     5.686975    9.014131    3.668677    4.275832
..         ...         ...         ...         ...
153   6.852877    9.272579    3.940863    3.775057
154   5.932245    8.913583    3.509633    4.305685
155   5.968708    8.670093    3.798473    4.360394
156   8.578665    9.168125    3.733853    4.356811
157   9.630366    8.851676    3.245011    4.304403

[158 rows x 4 columns]

In [20]:
# Variables transformation for equation
lnCT = np.log(ct) # lnCT
y = pd.Series(lnCT)
lnq = np.log(q) # lnq
lnqq = np.square(lnq) # lnq^2
lnp1 = np.log(p1) # lnp_1
lnp2 = np.log(p2) # lnp_2
lnp3 = np.log(p3) # lnp_3
lnqp1 = np.multiply(lnq, lnp1) # lnq*lnp_1
lnqp2 = np.multiply(lnq, lnp2) # lnq*lnp_2
lnqp3 = np.multiply(lnq, lnp3) # lnq*lnp_3
lnp11 = np.square(lnp1) # lnp_1^2
lnp22 = np.square(lnp2)  # lnp_2^2
lnp33 = np.square(lnp3)  # lnp_3^2
lnp1lnp2 = np.multiply(lnp1, lnp2) # lnp_1*lnp_2
lnp1lnp3 = np.multiply(lnp1, lnp3) # lnp_1*lnp_3
lnp2lnp3 = np.multiply(lnp2, lnp3) # lnp_2*lnp_3

# Defining matrices 
X = np.asarray([lnq, lnqq, lnqp1, lnqp2, lnqp3, lnp1, lnp2, lnp3, lnp11, lnp22, lnp33, 
                         lnp1lnp2, lnp1lnp3, lnp2lnp3]).T

# label of coefficients
betas = ["beta_lnq", "beta_lnq^2", "beta_lnqp1", "beta_lnqp2",
          "beta_lnqp3", "beta_lnp1", "beta_lnp2", "beta_lnp3", "beta_lnp1^2",
          "beta_lnp2^2", "beta_lnp3^2", "beta_lnp1lnp2", "beta_lnp1lnp3", "beta_lnp2lnp3"]

X_mat = pd.DataFrame(X)
X_mat.columns = betas

In [18]:
def beta_OLS(x: pd.DataFrame, y: pd.Series, intercept = True):
    
    if not isinstance( x , pd.DataFrame ):
        raise TypeError( "X variable is not pd.DataFrame.")
        
    if not isinstance( y, pd.Series ):
        raise TypeError( "Y variable is not pd.Series.")
    
    if not isinstance( intercept, bool ):
        raise TypeError( " Intercept is not a bool")
    
    X = x.copy()
    if (intercept == True):
        intercept = np.ones( len(x))  
        X.insert(0, "Intercept", intercept, True)
    
    names = list(X.columns)

    result = np.linalg.inv(X.T @ X) @ (X.T @ y)
    result_1 = pd.DataFrame(result, index = names, columns = ['Coef.'])
    return result_1

In [21]:
beta_OLS(X_mat, y, intercept = True)

                   Coef.
Intercept     -76.259257
beta_lnq       -1.080425
beta_lnq^2      0.026489
beta_lnqp1      0.131041
beta_lnqp2      0.058652
beta_lnqp3      0.040144
beta_lnp1      14.718292
beta_lnp2      -0.894733
beta_lnp3       6.380797
beta_lnp1^2    -0.769264
beta_lnp2^2    -0.036753
beta_lnp3^2    -0.163707
beta_lnp1lnp2   0.162283
beta_lnp1lnp3  -0.572050
beta_lnp2lnp3  -0.024025

2. Generate a new function named **var_OLS**. This function must return the estimated variance for OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated variance does not include **intercept** in the `X` regressor. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The output of the function should look like `var_ols` where the columns and the index use the name of `X` columns.  Apply your function to find $\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)})$ of the equation below. Use greene data.  **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**


$$
\begin{aligned}
\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)}) = 
\sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [22]:
var_OLS_output = results.fit().cov_params()

In [23]:
var_OLS_output

            Intercept  np.log(Q)  np.log(PL)  np.log(PF)  np.log(PK)
Intercept    1.130476   0.001167   -0.104116    0.004928   -0.052305
np.log(Q)    0.001167   0.000088   -0.000179    0.000055   -0.000111
np.log(PL)  -0.104116  -0.000179    0.011198   -0.001794    0.002636
np.log(PF)   0.004928   0.000055   -0.001794    0.004142   -0.000782
np.log(PK)  -0.052305  -0.000111    0.002636   -0.000782    0.007581

In [24]:
def var_OLS(x: pd.DataFrame, y: pd.Series, intercept  = True):
    
    if not isinstance( x , pd.DataFrame ):
        raise TypeError( "X variable is not pd.DataFrame.")
        
    if not isinstance( y, pd.Series ):
        raise TypeError( "Y variable is not pd.Series.")
    
    if not isinstance( intercept, bool ):
        raise TypeError( "Intercept is not a bool")
        
    X = x.copy()
    
    if (intercept == True):
        intercept = np.ones( len(x))
        X.insert(0, "Intercept", intercept, True)
    
    names = list(X.columns)

    result = np.linalg.inv(X.T @ X) @ (X.T @ y)

    # Defining errors and variance
    res = y - X @ result
    sigma_sqr = ( res.T @ res) / (len(y)-(len(result)))

    # getting var_beta_ols
    var_ols = sigma_sqr * np.linalg.inv(X.T @ X)
    
    var_ols = pd.DataFrame(var_ols, index = names, columns = names)
    return var_ols

In [28]:
var_OLS(X_mat, y, intercept  = True)

,Intercept,beta_lnq,beta_lnq^2,beta_lnqp1,beta_lnqp2,beta_lnqp3,beta_lnp1,beta_lnp2,beta_lnp3,beta_lnp1^2,beta_lnp2^2,beta_lnp3^2,beta_lnp1lnp2,beta_lnp1lnp3,beta_lnp2lnp3
Intercept,1465.361097,0.192537,-0.011698,-0.026677,0.015949,0.039538,-262.932563,-8.392679,-128.192044,11.880856,-0.266944,3.540639,0.990253,10.902440,0.197435
beta_lnq,0.192537,0.141034,0.000308,-0.013459,0.000161,-0.006089,-0.186223,0.148320,-0.090714,0.015321,0.000381,-0.000898,-0.015046,0.017546,-0.003570
beta_lnq^2,-0.011698,0.000308,0.000006,-0.000036,-0.000005,-0.000011,0.001491,0.001052,0.000862,-0.000043,0.000013,-0.000060,-0.000099,-0.000014,-0.000048
beta_lnqp1,-0.026677,-0.013459,-0.000036,0.001466,-0.000168,0.000348,0.021561,-0.015127,0.005430,-0.001961,0.000019,0.000285,0.001850,-0.001141,-0.000085
beta_lnqp2,0.015949,0.000161,-0.000005,-0.000168,0.000653,-0.000189,-0.008293,0.003306,0.008035,0.000587,-0.000170,-0.000103,-0.000170,-0.000144,-0.001375
beta_lnqp3,0.039538,-0.006089,-0.000011,0.000348,-0.000189,0.000888,-0.000337,-0.008853,0.000268,0.000211,-0.000033,-0.000067,0.000102,-0.001537,0.002212
beta_lnp1,-262.932563,-0.186223,0.001491,0.021561,-0.008293,-0.000337,50.194721,-1.253531,19.099542,-2.388986,0.070493,-0.420154,0.038416,-1.788158,0.132157
beta_lnp2,-8.392679,0.148320,0.001052,-0.015127,0.003306,-0.008853,-1.253531,8.078742,-0.214871,0.161643,-0.058647,-0.033147,-0.685050,0.199482,-0.367388
beta_lnp3,-128.192044,-0.090714,0.000862,0.005430,0.008035,0.000268,19.099542,-0.214871,20.513714,-0.705214,0.023665,-0.763050,0.036229,-1.555553,-0.072591
beta_lnp1^2,11.880856,0.015321,-0.000043,-0.001961,0.000587,0.000211,-2.388986,0.161643,-0.705214,0.119855,-0.003079,0.011353,-0.013413,0.070381,-0.006656
beta_lnp2^2,-0.266944,0.000381,0.000013,0.000019,-0.000170,-0.000033,0.070493,-0.058647,0.023665,-0.003079,0.008285,-0.002049,-0.001552,-0.002485,0.004467
beta_lnp3^2,3.540639,-0.000898,-0.000060,0.000285,-0.000103,-0.000067,-0.420154,-0.033147,-0.763050,0.011353,-0.002049,0.048556,0.008386,0.043314,-0.006653
beta_lnp1lnp2,0.990253,-0.015046,-0.000099,0.001850,-0.000170,0.000102,0.038416,-0.685050,0.036229,-0.013413,-0.001552,0.008386,0.072939,-0.015413,0.009949
beta_lnp1lnp3,10.902440,0.017546,-0.000014,-0.001141,-0.000144,-0.001537,-1.788158,0.199482,-1.555553,0.070381,-0.002485,0.043314,-0.015413,0.138302,-0.010534
beta_lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,-0.001375,0.002212,0.132157,-0.367388,-0.072591,-0.006656,0.004467,-0.006653,0.009949,-0.010534,0.060678

3. Generate a new function named as `reg_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the output does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. Apply your function to the equation below. Use greene data.**Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [26]:
reg_OLS_output = results.fit().summary2().tables[1]
reg_OLS_output

               Coef.  Std.Err.          t          P>|t|    [0.025    0.975]
Intercept  -7.472227  1.063238  -7.027801   6.490901e-11 -9.572750 -5.371704
np.log(Q)   0.838111  0.009387  89.284492  6.942379e-134  0.819566  0.856656
np.log(PL)  0.044258  0.105820   0.418238   6.763595e-01 -0.164798  0.253314
np.log(PF)  0.713098  0.064355  11.080610   2.552882e-21  0.585958  0.840238
np.log(PK)  0.188449  0.087066   2.164432   3.198211e-02  0.016442  0.360457

In [1]:
import scipy.stats as stats

In [34]:
def reg_OLS(x: pd.DataFrame, y: pd.Series, intercept = True):
    
    if not isinstance( x , pd.DataFrame ):
        raise TypeError( "X variable is not pd.DataFrame type.")
        
    if not isinstance( y, pd.Series ):
        raise TypeError( "Y variable is not pd.Series type.")
    
    if not isinstance( intercept, bool ):
        raise TypeError( " Intercept is not a bool")
        
    X = x.copy()
    
    if (intercept == True):
        intercept = np.ones( len(x))
        X.insert(0, "Intercept", intercept, True)
   
        
    # Defining beta ols
    result = np.linalg.inv(X.T @ X) @ (X.T @ y)
    
    # Defining errors and variance
    res = y - X @ result
    sigma_sqr = ( res.T @ res) / (len(y)-(len(result)))

    # getting var_beta_ols
    var_ols = sigma_sqr * np.linalg.inv(X.T @ X) 
    
    # Standard errors of the estimated coefficients
    stderr = np.sqrt(np.diagonal(var_ols))

    # t values
    t_values = result/ stderr
    
    # P-values
    p_value = 2 * stats.t.cdf(x = -np.abs(t_values), df = len(y) - len(result))
    
    #  Calculate the confidence intervals:
    lower = result - stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(result)) * stderr
    upper = result + stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(result)) * stderr
    
    final_output = pd.DataFrame()
    final_output["Coef"],final_output["Std.Err."], final_output["t"], final_output["P>|t|"], final_output["[0.025"], final_output["0.975]"] = [result, stderr, t_values, p_value, lower, upper]
    
    #betas = ['Intercept','np.log(Q)', 'np.log(PL)', 'np.log(PF)', 'np.log(PK)']
    names = list(X.columns)
    final_output.index = names
    
    return final_output

In [35]:
reg_OLS(X_mat, y, intercept  = True)

,Coef,Std.Err.,t,P>|t|,[0.025,0.975]
Intercept,-76.259257,38.280035,-1.992142,4.825953e-02,-151.927104,-0.591410
beta_lnq,-1.080425,0.375545,-2.876952,4.630885e-03,-1.822762,-0.338088
beta_lnq^2,0.026489,0.002357,11.240060,2.112040e-21,0.021831,0.031148
beta_lnqp1,0.131041,0.038284,3.422854,8.084865e-04,0.055365,0.206716
beta_lnqp2,0.058652,0.025549,2.295650,2.315002e-02,0.008149,0.109155
beta_lnqp3,0.040144,0.029791,1.347518,1.799447e-01,-0.018744,0.099033
beta_lnp1,14.718292,7.084823,2.077440,3.954950e-02,0.713777,28.722807
beta_lnp2,-0.894733,2.842313,-0.314790,7.533796e-01,-6.513110,4.723645
beta_lnp3,6.380797,4.529207,1.408811,1.610617e-01,-2.572051,15.333644
beta_lnp1^2,-0.769264,0.346201,-2.222011,2.785341e-02,-1.453597,-0.084930
beta_lnp2^2,-0.036753,0.091019,-0.403791,6.869699e-01,-0.216670,0.143165
beta_lnp3^2,-0.163707,0.220354,-0.742927,4.587448e-01,-0.599280,0.271866
beta_lnp1lnp2,0.162283,0.270072,0.600888,5.488659e-01,-0.371566,0.696132
beta_lnp1lnp3,-0.572050,0.371890,-1.538224,1.262037e-01,-1.307163,0.163062
beta_lnp2lnp3,-0.024025,0.246329,-0.097531,9.224414e-01,-0.510942,0.462892

4. Generate a new function named as `restricted_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`,  `L`, `r`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series**,  `L` (coef) must be a **np.array**, `r` must be a **np.array**,  and `intercept` can be `True` or `False`.  When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `reg_OLS_ouput`. Apply your function to the equation below. Use greene data.
 **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\hat{\boldsymbol{\beta}}^{(RLS)} =\hat{\boldsymbol{\beta}}^{(OLS)} - \left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \left( \boldsymbol{L}\left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \right)^{-1} \left( \boldsymbol{L}\widehat{\boldsymbol{\beta}}^{(OLS)} - \boldsymbol{r} \right)
$$

$$
\begin{aligned}
\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right) 
&= \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1} - \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}  \mathbf{L}^\top \left( \mathbf{L}\left( \mathbf{X}^\top \mathbf{X} \right)^{-1} \mathbf{L}^\top \right)^{-1}  \mathbf{L} \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

5. Generate a new class named `RegClass`. The initial attributes of your class must be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. Also, you must specify the type of your class' parameters, and output and It must raise an error if the inputs do not meet the requirements.  This class should have two methods: `reg_OLS` and `restricted_OLS` (You can add more if you think it is necessary). These methods should return the same output as the previously defined functions with the same name. The method `reg_OLS` does not need an extra parameter to be executed. After executing the method `reg_OLS`, any user should access the following attributes: `beta_OLS` and `var_OLS`. They should look like `beta_OLS_output` and `var_OLS_output`. The `restricted_OLS` method needs two extra parameters before being executed, `L` and `r`. They refer to the restrictions. After running the method `restricted_OLS`, any user should access the following attributes: `beta_OLS`, `var_OLS`, `rest_beta_OLS`, and `rest_var_OLS`. These attributes refer to the beta and variance estimated using OLS and restricted OLS. They should look like  `beta_OLS_output` and `var_OLS_output`. Fix all the methods and attributes. No user should be able to change them. **Hint: Use [lecture 6](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f362f4c6563747572655f362e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_6%2FLecture_6.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96#6.3.).**

In [12]:
beta_OLS_output

               Coef.
Intercept  -7.472227
np.log(Q)   0.838111
np.log(PL)  0.044258
np.log(PF)  0.713098
np.log(PK)  0.188449

In [13]:
var_OLS_output

            Intercept  np.log(Q)  np.log(PL)  np.log(PF)  np.log(PK)
Intercept    1.130476   0.001167   -0.104116    0.004928   -0.052305
np.log(Q)    0.001167   0.000088   -0.000179    0.000055   -0.000111
np.log(PL)  -0.104116  -0.000179    0.011198   -0.001794    0.002636
np.log(PF)   0.004928   0.000055   -0.001794    0.004142   -0.000782
np.log(PK)  -0.052305  -0.000111    0.002636   -0.000782    0.007581